/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Student = IDL.Record({
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'registrationNumber' : IDL.Text,
  'batch' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AttendanceType = IDL.Variant({
  'practical' : IDL.Null,
  'theory' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'conductedClasses' : IDL.Nat,
  'studentReg' : IDL.Text,
  'attendedClasses' : IDL.Nat,
  'attendanceType' : AttendanceType,
  'subjectId' : IDL.Text,
});
export const MarksRecord = IDL.Record({
  'paper1' : IDL.Nat,
  'paper2' : IDL.Nat,
  'marksType' : AttendanceType,
  'studentReg' : IDL.Text,
  'subjectId' : IDL.Text,
});
export const Time = IDL.Int;
export const AnnouncementCategory = IDL.Variant({
  'exam' : IDL.Null,
  'academic' : IDL.Null,
  'urgent' : IDL.Null,
  'general' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'category' : AnnouncementCategory,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : Time,
  'message' : IDL.Text,
});
export const SubjectType = IDL.Variant({
  'practical' : IDL.Null,
  'both' : IDL.Null,
  'theory' : IDL.Null,
});
export const Subject = IDL.Record({
  'id' : IDL.Text,
  'subjectType' : SubjectType,
  'name' : IDL.Text,
  'year' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'registrationNumber' : IDL.Opt(IDL.Text),
});
export const CollegeInfo = IDL.Record({
  'contact' : IDL.Text,
  'about' : IDL.Text,
  'principalName' : IDL.Text,
});
export const SubjectAttendance = IDL.Record({
  'theoryMarks' : IDL.Opt(MarksRecord),
  'subject' : Subject,
  'practicalAttendance' : IDL.Opt(AttendanceRecord),
  'practicalMarks' : IDL.Opt(MarksRecord),
  'theoryAttendance' : IDL.Opt(AttendanceRecord),
});
export const Dashboard = IDL.Record({
  'subjects' : IDL.Vec(SubjectAttendance),
  'student' : Student,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const AdminAccessRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'requestorName' : IDL.Text,
  'department' : IDL.Text,
  'reason' : IDL.Text,
});
export const QueryStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
});
export const StudentQuery = IDL.Record({
  'id' : IDL.Text,
  'status' : QueryStatus,
  'adminReply' : IDL.Opt(IDL.Text),
  'studentName' : IDL.Text,
  'subject' : IDL.Text,
  'submittedAt' : Time,
  'studentReg' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSecondaryAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addStudent' : IDL.Func([Student], [], []),
  'approveAdminAccessRequest' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpsertAttendance' : IDL.Func([IDL.Vec(AttendanceRecord)], [], []),
  'bulkUpsertMarks' : IDL.Func([IDL.Vec(MarksRecord)], [], []),
  'bulkUpsertStudents' : IDL.Func([IDL.Vec(Student)], [], []),
  'changeAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'createAnnouncement' : IDL.Func([Announcement], [], []),
  'createNotification' : IDL.Func([Notification], [], []),
  'createSubject' : IDL.Func([Subject], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Text], [], []),
  'deleteNotification' : IDL.Func([IDL.Text], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'deleteSubject' : IDL.Func([IDL.Text], [], []),
  'generateId' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollegeInfo' : IDL.Func([], [IDL.Opt(CollegeInfo)], ['query']),
  'getStudentDashboard' : IDL.Func([IDL.Text], [IDL.Opt(Dashboard)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdminAccessRequests' : IDL.Func(
      [],
      [IDL.Vec(AdminAccessRequest)],
      ['query'],
    ),
  'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'listQueries' : IDL.Func([], [IDL.Vec(StudentQuery)], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'rejectAdminAccessRequest' : IDL.Func([IDL.Text], [], []),
  'replyToStudentQuery' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'submitAdminAccessRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitStudentQuery' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateAnnouncement' : IDL.Func([Announcement], [], []),
  'updateCollegeInfo' : IDL.Func([CollegeInfo], [], []),
  'updateNotification' : IDL.Func([Notification], [], []),
  'updateStudent' : IDL.Func([Student], [], []),
  'updateSubject' : IDL.Func([Subject], [], []),
  'verifyAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Student = IDL.Record({
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'registrationNumber' : IDL.Text,
    'batch' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AttendanceType = IDL.Variant({
    'practical' : IDL.Null,
    'theory' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'conductedClasses' : IDL.Nat,
    'studentReg' : IDL.Text,
    'attendedClasses' : IDL.Nat,
    'attendanceType' : AttendanceType,
    'subjectId' : IDL.Text,
  });
  const MarksRecord = IDL.Record({
    'paper1' : IDL.Nat,
    'paper2' : IDL.Nat,
    'marksType' : AttendanceType,
    'studentReg' : IDL.Text,
    'subjectId' : IDL.Text,
  });
  const Time = IDL.Int;
  const AnnouncementCategory = IDL.Variant({
    'exam' : IDL.Null,
    'academic' : IDL.Null,
    'urgent' : IDL.Null,
    'general' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'category' : AnnouncementCategory,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : Time,
    'message' : IDL.Text,
  });
  const SubjectType = IDL.Variant({
    'practical' : IDL.Null,
    'both' : IDL.Null,
    'theory' : IDL.Null,
  });
  const Subject = IDL.Record({
    'id' : IDL.Text,
    'subjectType' : SubjectType,
    'name' : IDL.Text,
    'year' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'registrationNumber' : IDL.Opt(IDL.Text),
  });
  const CollegeInfo = IDL.Record({
    'contact' : IDL.Text,
    'about' : IDL.Text,
    'principalName' : IDL.Text,
  });
  const SubjectAttendance = IDL.Record({
    'theoryMarks' : IDL.Opt(MarksRecord),
    'subject' : Subject,
    'practicalAttendance' : IDL.Opt(AttendanceRecord),
    'practicalMarks' : IDL.Opt(MarksRecord),
    'theoryAttendance' : IDL.Opt(AttendanceRecord),
  });
  const Dashboard = IDL.Record({
    'subjects' : IDL.Vec(SubjectAttendance),
    'student' : Student,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const AdminAccessRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'requestorName' : IDL.Text,
    'department' : IDL.Text,
    'reason' : IDL.Text,
  });
  const QueryStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
  });
  const StudentQuery = IDL.Record({
    'id' : IDL.Text,
    'status' : QueryStatus,
    'adminReply' : IDL.Opt(IDL.Text),
    'studentName' : IDL.Text,
    'subject' : IDL.Text,
    'submittedAt' : Time,
    'studentReg' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSecondaryAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addStudent' : IDL.Func([Student], [], []),
    'approveAdminAccessRequest' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpsertAttendance' : IDL.Func([IDL.Vec(AttendanceRecord)], [], []),
    'bulkUpsertMarks' : IDL.Func([IDL.Vec(MarksRecord)], [], []),
    'bulkUpsertStudents' : IDL.Func([IDL.Vec(Student)], [], []),
    'changeAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'createAnnouncement' : IDL.Func([Announcement], [], []),
    'createNotification' : IDL.Func([Notification], [], []),
    'createSubject' : IDL.Func([Subject], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Text], [], []),
    'deleteNotification' : IDL.Func([IDL.Text], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'deleteSubject' : IDL.Func([IDL.Text], [], []),
    'generateId' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollegeInfo' : IDL.Func([], [IDL.Opt(CollegeInfo)], ['query']),
    'getStudentDashboard' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Dashboard)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdminAccessRequests' : IDL.Func(
        [],
        [IDL.Vec(AdminAccessRequest)],
        ['query'],
      ),
    'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'listQueries' : IDL.Func([], [IDL.Vec(StudentQuery)], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'rejectAdminAccessRequest' : IDL.Func([IDL.Text], [], []),
    'replyToStudentQuery' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'submitAdminAccessRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitStudentQuery' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateAnnouncement' : IDL.Func([Announcement], [], []),
    'updateCollegeInfo' : IDL.Func([CollegeInfo], [], []),
    'updateNotification' : IDL.Func([Notification], [], []),
    'updateStudent' : IDL.Func([Student], [], []),
    'updateSubject' : IDL.Func([Subject], [], []),
    'verifyAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };