/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAccessRequest {
  'id' : string,
  'status' : RequestStatus,
  'submittedAt' : Time,
  'email' : string,
  'requestorName' : string,
  'department' : string,
  'reason' : string,
}
export interface Announcement {
  'id' : string,
  'title' : string,
  'content' : string,
  'date' : Time,
  'category' : AnnouncementCategory,
}
export type AnnouncementCategory = { 'exam' : null } |
  { 'academic' : null } |
  { 'urgent' : null } |
  { 'general' : null };
export interface AttendanceRecord {
  'conductedClasses' : bigint,
  'studentReg' : string,
  'attendedClasses' : bigint,
  'attendanceType' : AttendanceType,
  'subjectId' : string,
}
export type AttendanceType = { 'practical' : null } |
  { 'theory' : null };
export interface CollegeInfo {
  'contact' : string,
  'about' : string,
  'principalName' : string,
}
export interface Dashboard {
  'subjects' : Array<SubjectAttendance>,
  'student' : Student,
}
export interface MarksRecord {
  'paper1' : bigint,
  'paper2' : bigint,
  'marksType' : AttendanceType,
  'studentReg' : string,
  'subjectId' : string,
}
export interface Notification {
  'id' : string,
  'title' : string,
  'date' : Time,
  'message' : string,
}
export type QueryStatus = { 'resolved' : null } |
  { 'pending' : null };
export type RequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Student {
  'name' : string,
  'year' : bigint,
  'registrationNumber' : string,
  'batch' : string,
}
export interface StudentQuery {
  'id' : string,
  'status' : QueryStatus,
  'adminReply' : [] | [string],
  'studentName' : string,
  'subject' : string,
  'submittedAt' : Time,
  'studentReg' : string,
  'message' : string,
}
export interface Subject {
  'id' : string,
  'subjectType' : SubjectType,
  'name' : string,
  'year' : bigint,
}
export interface SubjectAttendance {
  'theoryMarks' : [] | [MarksRecord],
  'subject' : Subject,
  'practicalAttendance' : [] | [AttendanceRecord],
  'practicalMarks' : [] | [MarksRecord],
  'theoryAttendance' : [] | [AttendanceRecord],
}
export type SubjectType = { 'practical' : null } |
  { 'both' : null } |
  { 'theory' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'registrationNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSecondaryAdmin' : ActorMethod<[string, string], undefined>,
  'addStudent' : ActorMethod<[Student], undefined>,
  'approveAdminAccessRequest' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpsertAttendance' : ActorMethod<[Array<AttendanceRecord>], undefined>,
  'bulkUpsertMarks' : ActorMethod<[Array<MarksRecord>], undefined>,
  'bulkUpsertStudents' : ActorMethod<[Array<Student>], undefined>,
  'changeAdminCredentials' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
  'createAnnouncement' : ActorMethod<[Announcement], undefined>,
  'createNotification' : ActorMethod<[Notification], undefined>,
  'createSubject' : ActorMethod<[Subject], undefined>,
  'deleteAnnouncement' : ActorMethod<[string], undefined>,
  'deleteNotification' : ActorMethod<[string], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'deleteSubject' : ActorMethod<[string], undefined>,
  'generateId' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollegeInfo' : ActorMethod<[], [] | [CollegeInfo]>,
  'getStudentDashboard' : ActorMethod<[string], [] | [Dashboard]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAdminAccessRequests' : ActorMethod<[], Array<AdminAccessRequest>>,
  'listAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'listNotifications' : ActorMethod<[], Array<Notification>>,
  'listQueries' : ActorMethod<[], Array<StudentQuery>>,
  'listStudents' : ActorMethod<[], Array<Student>>,
  'listSubjects' : ActorMethod<[], Array<Subject>>,
  'rejectAdminAccessRequest' : ActorMethod<[string], undefined>,
  'replyToStudentQuery' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchStudent' : ActorMethod<[string], [] | [Student]>,
  'submitAdminAccessRequest' : ActorMethod<
    [string, string, string, string],
    string
  >,
  'submitStudentQuery' : ActorMethod<[string, string, string, string], string>,
  'updateAnnouncement' : ActorMethod<[Announcement], undefined>,
  'updateCollegeInfo' : ActorMethod<[CollegeInfo], undefined>,
  'updateNotification' : ActorMethod<[Notification], undefined>,
  'updateStudent' : ActorMethod<[Student], undefined>,
  'updateSubject' : ActorMethod<[Subject], undefined>,
  'verifyAdminCredentials' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];