/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SubjectAttendance {
    theoryMarks?: MarksRecord;
    subject: Subject;
    practicalAttendance?: AttendanceRecord;
    practicalMarks?: MarksRecord;
    theoryAttendance?: AttendanceRecord;
}
export interface StudentQuery {
    id: string;
    status: QueryStatus;
    adminReply?: string;
    studentName: string;
    subject: string;
    submittedAt: Time;
    studentReg: string;
    message: string;
}
export interface AdminAccessRequest {
    id: string;
    status: RequestStatus;
    submittedAt: Time;
    email: string;
    requestorName: string;
    department: string;
    reason: string;
}
export type Time = bigint;
export interface CollegeInfo {
    contact: string;
    about: string;
    principalName: string;
}
export interface MarksRecord {
    marks: bigint;
    marksType: AttendanceType;
    studentReg: string;
    subjectId: string;
}
export interface Notification {
    id: string;
    title: string;
    date: Time;
    message: string;
}
export interface Dashboard {
    subjects: Array<SubjectAttendance>;
    student: Student;
}
export interface Announcement {
    id: string;
    title: string;
    content: string;
    date: Time;
    category: AnnouncementCategory;
}
export interface AttendanceRecord {
    conductedClasses: bigint;
    studentReg: string;
    attendedClasses: bigint;
    attendanceType: AttendanceType;
    subjectId: string;
}
export interface Subject {
    id: string;
    subjectType: SubjectType;
    name: string;
    year: bigint;
}
export interface UserProfile {
    name: string;
    registrationNumber?: string;
}
export interface Student {
    name: string;
    year: bigint;
    registrationNumber: string;
    batch: string;
}
export enum AnnouncementCategory {
    exam = "exam",
    academic = "academic",
    urgent = "urgent",
    general = "general"
}
export enum AttendanceType {
    practical = "practical",
    theory = "theory"
}
export enum QueryStatus {
    resolved = "resolved",
    pending = "pending"
}
export enum RequestStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum SubjectType {
    practical = "practical",
    both = "both",
    theory = "theory"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSecondaryAdmin(username: string, password: string): Promise<void>;
    addStudent(student: Student): Promise<void>;
    approveAdminAccessRequest(id: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkUpsertAttendance(records: Array<AttendanceRecord>): Promise<void>;
    bulkUpsertMarks(records: Array<MarksRecord>): Promise<void>;
    bulkUpsertStudents(studentsArray: Array<Student>): Promise<void>;
    changeAdminCredentials(oldUsername: string, oldPassword: string, newUsername: string, newPassword: string): Promise<boolean>;
    createAnnouncement(announcement: Announcement): Promise<void>;
    createNotification(notification: Notification): Promise<void>;
    createSubject(subject: Subject): Promise<void>;
    deleteAnnouncement(id: string): Promise<void>;
    deleteNotification(id: string): Promise<void>;
    deleteStudent(registrationNumber: string): Promise<void>;
    deleteSubject(id: string): Promise<void>;
    generateId(prefix: string): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCollegeInfo(): Promise<CollegeInfo | null>;
    getStudentDashboard(registrationNumber: string): Promise<Dashboard | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAdminAccessRequests(): Promise<Array<AdminAccessRequest>>;
    listAnnouncements(): Promise<Array<Announcement>>;
    listNotifications(): Promise<Array<Notification>>;
    listQueries(): Promise<Array<StudentQuery>>;
    listStudents(): Promise<Array<Student>>;
    listSubjects(): Promise<Array<Subject>>;
    rejectAdminAccessRequest(id: string): Promise<void>;
    replyToStudentQuery(id: string, reply: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchStudent(registrationNumber: string): Promise<Student | null>;
    submitAdminAccessRequest(requestorName: string, email: string, department: string, reason: string): Promise<string>;
    submitStudentQuery(studentReg: string, studentName: string, subject: string, message: string): Promise<string>;
    updateAnnouncement(announcement: Announcement): Promise<void>;
    updateCollegeInfo(info: CollegeInfo): Promise<void>;
    updateNotification(notification: Notification): Promise<void>;
    updateStudent(student: Student): Promise<void>;
    updateSubject(subject: Subject): Promise<void>;
    verifyAdminCredentials(username: string, password: string): Promise<boolean>;
}
import type { AdminAccessRequest as _AdminAccessRequest, Announcement as _Announcement, AnnouncementCategory as _AnnouncementCategory, AttendanceRecord as _AttendanceRecord, AttendanceType as _AttendanceType, CollegeInfo as _CollegeInfo, Dashboard as _Dashboard, MarksRecord as _MarksRecord, QueryStatus as _QueryStatus, RequestStatus as _RequestStatus, Student as _Student, StudentQuery as _StudentQuery, Subject as _Subject, SubjectAttendance as _SubjectAttendance, SubjectType as _SubjectType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSecondaryAdmin(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSecondaryAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSecondaryAdmin(arg0, arg1);
            return result;
        }
    }
    async addStudent(arg0: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0);
            return result;
        }
    }
    async approveAdminAccessRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveAdminAccessRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveAdminAccessRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkUpsertAttendance(arg0: Array<AttendanceRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpsertAttendance(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpsertAttendance(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bulkUpsertMarks(arg0: Array<MarksRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpsertMarks(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpsertMarks(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bulkUpsertStudents(arg0: Array<Student>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpsertStudents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpsertStudents(arg0);
            return result;
        }
    }
    async changeAdminCredentials(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminCredentials(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminCredentials(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createAnnouncement(arg0: Announcement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(to_candid_Announcement_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(to_candid_Announcement_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createNotification(arg0: Notification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0);
            return result;
        }
    }
    async createSubject(arg0: Subject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubject(to_candid_Subject_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubject(to_candid_Subject_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAnnouncement(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async deleteNotification(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotification(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteSubject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubject(arg0);
            return result;
        }
    }
    async generateId(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateId(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollegeInfo(): Promise<CollegeInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollegeInfo();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollegeInfo();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentDashboard(arg0: string): Promise<Dashboard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentDashboard(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentDashboard(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAdminAccessRequests(): Promise<Array<AdminAccessRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAdminAccessRequests();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAdminAccessRequests();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnnouncements();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnnouncements();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotifications();
            return result;
        }
    }
    async listQueries(): Promise<Array<StudentQuery>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQueries();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQueries();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents();
            return result;
        }
    }
    async listSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubjects();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubjects();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectAdminAccessRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectAdminAccessRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectAdminAccessRequest(arg0);
            return result;
        }
    }
    async replyToStudentQuery(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replyToStudentQuery(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyToStudentQuery(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n60(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n60(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchStudent(arg0: string): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudent(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudent(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAdminAccessRequest(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAdminAccessRequest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAdminAccessRequest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitStudentQuery(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitStudentQuery(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitStudentQuery(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateAnnouncement(arg0: Announcement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(to_candid_Announcement_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(to_candid_Announcement_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCollegeInfo(arg0: CollegeInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollegeInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollegeInfo(arg0);
            return result;
        }
    }
    async updateNotification(arg0: Notification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotification(arg0);
            return result;
        }
    }
    async updateStudent(arg0: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0);
            return result;
        }
    }
    async updateSubject(arg0: Subject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubject(to_candid_Subject_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubject(to_candid_Subject_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyAdminCredentials(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminCredentials(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AdminAccessRequest_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminAccessRequest): AdminAccessRequest {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_AnnouncementCategory_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnouncementCategory): AnnouncementCategory {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Announcement_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Announcement): Announcement {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceRecord_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceType): AttendanceType {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Dashboard_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dashboard): Dashboard {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_MarksRecord_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarksRecord): MarksRecord {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_QueryStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueryStatus): QueryStatus {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_StudentQuery_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentQuery): StudentQuery {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_SubjectAttendance_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubjectAttendance): SubjectAttendance {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_SubjectType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubjectType): SubjectType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CollegeInfo]): CollegeInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Dashboard]): Dashboard | null {
    return value.length === 0 ? null : from_candid_Dashboard_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarksRecord]): MarksRecord | null {
    return value.length === 0 ? null : from_candid_MarksRecord_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AttendanceRecord]): AttendanceRecord | null {
    return value.length === 0 ? null : from_candid_AttendanceRecord_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    registrationNumber: [] | [string];
}): {
    name: string;
    registrationNumber?: string;
} {
    return {
        name: value.name,
        registrationNumber: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.registrationNumber))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjects: Array<_SubjectAttendance>;
    student: _Student;
}): {
    subjects: Array<SubjectAttendance>;
    student: Student;
} {
    return {
        subjects: from_candid_vec_n29(_uploadFile, _downloadFile, value.subjects),
        student: value.student
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theoryMarks: [] | [_MarksRecord];
    subject: _Subject;
    practicalAttendance: [] | [_AttendanceRecord];
    practicalMarks: [] | [_MarksRecord];
    theoryAttendance: [] | [_AttendanceRecord];
}): {
    theoryMarks?: MarksRecord;
    subject: Subject;
    practicalAttendance?: AttendanceRecord;
    practicalMarks?: MarksRecord;
    theoryAttendance?: AttendanceRecord;
} {
    return {
        theoryMarks: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.theoryMarks)),
        subject: from_candid_Subject_n37(_uploadFile, _downloadFile, value.subject),
        practicalAttendance: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.practicalAttendance)),
        practicalMarks: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.practicalMarks)),
        theoryAttendance: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.theoryAttendance))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marks: bigint;
    marksType: _AttendanceType;
    studentReg: string;
    subjectId: string;
}): {
    marks: bigint;
    marksType: AttendanceType;
    studentReg: string;
    subjectId: string;
} {
    return {
        marks: value.marks,
        marksType: from_candid_AttendanceType_n35(_uploadFile, _downloadFile, value.marksType),
        studentReg: value.studentReg,
        subjectId: value.subjectId
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    subjectType: _SubjectType;
    name: string;
    year: bigint;
}): {
    id: string;
    subjectType: SubjectType;
    name: string;
    year: bigint;
} {
    return {
        id: value.id,
        subjectType: from_candid_SubjectType_n39(_uploadFile, _downloadFile, value.subjectType),
        name: value.name,
        year: value.year
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    conductedClasses: bigint;
    studentReg: string;
    attendedClasses: bigint;
    attendanceType: _AttendanceType;
    subjectId: string;
}): {
    conductedClasses: bigint;
    studentReg: string;
    attendedClasses: bigint;
    attendanceType: AttendanceType;
    subjectId: string;
} {
    return {
        conductedClasses: value.conductedClasses,
        studentReg: value.studentReg,
        attendedClasses: value.attendedClasses,
        attendanceType: from_candid_AttendanceType_n35(_uploadFile, _downloadFile, value.attendanceType),
        subjectId: value.subjectId
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _RequestStatus;
    submittedAt: _Time;
    email: string;
    requestorName: string;
    department: string;
    reason: string;
}): {
    id: string;
    status: RequestStatus;
    submittedAt: Time;
    email: string;
    requestorName: string;
    department: string;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_RequestStatus_n47(_uploadFile, _downloadFile, value.status),
        submittedAt: value.submittedAt,
        email: value.email,
        requestorName: value.requestorName,
        department: value.department,
        reason: value.reason
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    date: _Time;
    category: _AnnouncementCategory;
}): {
    id: string;
    title: string;
    content: string;
    date: Time;
    category: AnnouncementCategory;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        date: value.date,
        category: from_candid_AnnouncementCategory_n52(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _QueryStatus;
    adminReply: [] | [string];
    studentName: string;
    subject: string;
    submittedAt: _Time;
    studentReg: string;
    message: string;
}): {
    id: string;
    status: QueryStatus;
    adminReply?: string;
    studentName: string;
    subject: string;
    submittedAt: Time;
    studentReg: string;
    message: string;
} {
    return {
        id: value.id,
        status: from_candid_QueryStatus_n57(_uploadFile, _downloadFile, value.status),
        adminReply: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.adminReply)),
        studentName: value.studentName,
        subject: value.subject,
        submittedAt: value.submittedAt,
        studentReg: value.studentReg,
        message: value.message
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    practical: null;
} | {
    theory: null;
}): AttendanceType {
    return "practical" in value ? AttendanceType.practical : "theory" in value ? AttendanceType.theory : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    practical: null;
} | {
    both: null;
} | {
    theory: null;
}): SubjectType {
    return "practical" in value ? SubjectType.practical : "both" in value ? SubjectType.both : "theory" in value ? SubjectType.theory : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): RequestStatus {
    return "pending" in value ? RequestStatus.pending : "approved" in value ? RequestStatus.approved : "rejected" in value ? RequestStatus.rejected : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exam: null;
} | {
    academic: null;
} | {
    urgent: null;
} | {
    general: null;
}): AnnouncementCategory {
    return "exam" in value ? AnnouncementCategory.exam : "academic" in value ? AnnouncementCategory.academic : "urgent" in value ? AnnouncementCategory.urgent : "general" in value ? AnnouncementCategory.general : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    pending: null;
}): QueryStatus {
    return "resolved" in value ? QueryStatus.resolved : "pending" in value ? QueryStatus.pending : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubjectAttendance>): Array<SubjectAttendance> {
    return value.map((x)=>from_candid_SubjectAttendance_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminAccessRequest>): Array<AdminAccessRequest> {
    return value.map((x)=>from_candid_AdminAccessRequest_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Announcement>): Array<Announcement> {
    return value.map((x)=>from_candid_Announcement_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentQuery>): Array<StudentQuery> {
    return value.map((x)=>from_candid_StudentQuery_n55(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subject>): Array<Subject> {
    return value.map((x)=>from_candid_Subject_n37(_uploadFile, _downloadFile, x));
}
function to_candid_AnnouncementCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementCategory): _AnnouncementCategory {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Announcement_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Announcement): _Announcement {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceRecord_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceRecord): _AttendanceRecord {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceType): _AttendanceType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_MarksRecord_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarksRecord): _MarksRecord {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_SubjectType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubjectType): _SubjectType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Subject_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): _Subject {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marks: bigint;
    marksType: AttendanceType;
    studentReg: string;
    subjectId: string;
}): {
    marks: bigint;
    marksType: _AttendanceType;
    studentReg: string;
    subjectId: string;
} {
    return {
        marks: value.marks,
        marksType: to_candid_AttendanceType_n6(_uploadFile, _downloadFile, value.marksType),
        studentReg: value.studentReg,
        subjectId: value.subjectId
    };
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    date: Time;
    category: AnnouncementCategory;
}): {
    id: string;
    title: string;
    content: string;
    date: _Time;
    category: _AnnouncementCategory;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        date: value.date,
        category: to_candid_AnnouncementCategory_n13(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    subjectType: SubjectType;
    name: string;
    year: bigint;
}): {
    id: string;
    subjectType: _SubjectType;
    name: string;
    year: bigint;
} {
    return {
        id: value.id,
        subjectType: to_candid_SubjectType_n17(_uploadFile, _downloadFile, value.subjectType),
        name: value.name,
        year: value.year
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    conductedClasses: bigint;
    studentReg: string;
    attendedClasses: bigint;
    attendanceType: AttendanceType;
    subjectId: string;
}): {
    conductedClasses: bigint;
    studentReg: string;
    attendedClasses: bigint;
    attendanceType: _AttendanceType;
    subjectId: string;
} {
    return {
        conductedClasses: value.conductedClasses,
        studentReg: value.studentReg,
        attendedClasses: value.attendedClasses,
        attendanceType: to_candid_AttendanceType_n6(_uploadFile, _downloadFile, value.attendanceType),
        subjectId: value.subjectId
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    registrationNumber?: string;
}): {
    name: string;
    registrationNumber: [] | [string];
} {
    return {
        name: value.name,
        registrationNumber: value.registrationNumber ? candid_some(value.registrationNumber) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementCategory): {
    exam: null;
} | {
    academic: null;
} | {
    urgent: null;
} | {
    general: null;
} {
    return value == AnnouncementCategory.exam ? {
        exam: null
    } : value == AnnouncementCategory.academic ? {
        academic: null
    } : value == AnnouncementCategory.urgent ? {
        urgent: null
    } : value == AnnouncementCategory.general ? {
        general: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubjectType): {
    practical: null;
} | {
    both: null;
} | {
    theory: null;
} {
    return value == SubjectType.practical ? {
        practical: null
    } : value == SubjectType.both ? {
        both: null
    } : value == SubjectType.theory ? {
        theory: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceType): {
    practical: null;
} | {
    theory: null;
} {
    return value == AttendanceType.practical ? {
        practical: null
    } : value == AttendanceType.theory ? {
        theory: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AttendanceRecord>): Array<_AttendanceRecord> {
    return value.map((x)=>to_candid_AttendanceRecord_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MarksRecord>): Array<_MarksRecord> {
    return value.map((x)=>to_candid_MarksRecord_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
